### ISSUE TITLE
Why the requirement of django < 1.10 ?

### ISSUE THREAD

**Issue by erikpotterbsx** [bharling/django-pint#1]
First off, thanks for starting this. I was just about to dive in and attempt to create something very similar to this either based on Pint or Unum.

I'm wondering what the reasoning is behind requiring Django version < 1.10 in your package setup. Were you just being cautious? I'm trying to see if I can use this with the latest version of Django (1.10.1) and based on the 1.10 release notes I'm not sure if the restriction is necessary.

Thanks!

**Comment by bharling** [comment]
Yeah I was just being a bit cautious I think - I'll add a tox entry for 1.10 when i get a chance and see how it fares. I dont remember any specific reason why it wouldnt work
