### ISSUE TITLE
Current quantity value not rendered in admin view

### ISSUE THREAD

**Issue by dylanjbarth** [bharling/django-pint#2]
Nice work on this, excited to help it develop.

I noticed that the value of the QuantityField is not displayed in the input box in the admin interface. I'm a django beginner, but if you point me in the right direction, happy to submit a pr.

**Comment by bharling** [comment]
Ah good catch, I'd done virtually no admin testing on this! I'll have a look.

**Comment by bharling** [comment]
This is fixed by PR #3 released on pypi
